// src/navbar/dropdowns/Art.jsx
import { useState } from "react";

function ArtDropdown(props) {
  const [mouseState, showNavbar] = useState(false);

  function enterHandler(){
    showNavbar(true);
  }
  function exitHandler(){
    showNavbar(false);
  }
  return (
    <div className="bottombarLinks">
      <a href="#" rel="noreferrer" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>Art</a>
      {mouseState ?
      (<div className="dropdownMenu" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/visit/plan-your-visit" target="_blank" rel="noreferrer">The Met Collection</a></div>
        <div className="dropdownLinks"><a href="https://engage.metmuseum.org/admission" target="_blank" rel="noreferrer">Curatorial Areas</a></div>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/join-and-give/membership" target="_blank" rel="noreferrer">Convservation and Scientific Research</a></div>
      </div>)
      :
      null}
    </div>
  );
}

export default ArtDropdown;

// yourmet-sveltekit/src/lib/navbar/dropdowns/Art.svelte
<script>
  import { fade } from "svelte/transition";
  let mouseState = false;
</script>

<div class="bottombarLinks" on:mouseenter={()=> mouseState = true} on:mouseleave={()=> mouseState = false}>
  <span class="bottombarText">Art</span>
  {#if mouseState}
  <div class="dropdownMenu" >
    <a href="https://www.metmuseum.org/art/the-collection" target="_blank" rel="noreferrer"><div class="dropdownLinks">The Met Collection</div></a>
    <a href="https://www.metmuseum.org/about-the-met/collection-areas" target="_blank" rel="noreferrer"><div class="dropdownLinks">Curatorial Areas</div></a>
    <a href="https://www.metmuseum.org/about-the-met/conservation-and-scientific-research" target="_blank" rel="noreferrer"><div class="dropdownLinks">Convservation and Scientific Research</div></a>
  </div>
  {/if}
</div>

<style>
  .bottombarLinks {
    min-width: 35px;
  }
</style>
