// src/navbar/dropdowns/Research.jsx
import { useState } from "react";

function ResearchDropdown(props) {
  const [mouseState, showNavbar] = useState(false);

  function enterHandler(){
    showNavbar(true);
  }
  function exitHandler(){
    showNavbar(false);
  }
  return (
    <div className="bottombarLinks">
      <a href="#" rel="noreferrer" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>Research</a>
      {mouseState ?
      <div className="dropdownMenu" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/art/libraries-and-research-centers" target="_blank" rel="noreferrer">Libraries and Research Centers</a></div>
      </div>
      :
      null
      }
    </div>
  );
}

export default ResearchDropdown;

// yourmet-sveltekit/src/lib/navbar/dropdowns/Research.svelte
<script>
  import { fade } from "svelte/transition";
  let mouseState = false;
</script>

<div class="bottombarLinks" on:mouseenter={()=> mouseState = true}  on:mouseleave={()=> mouseState = false}>
  <span class="bottombarText">Research</span>
  {#if mouseState}
  <div class="dropdownMenu">
    <a href="https://www.metmuseum.org/art/libraries-and-research-centers" target="_blank" rel="noreferrer"><div class="dropdownLinks">Libraries and Research Centers</div></a>
  </div>
  {/if}
</div>

<style>
  .bottombarLinks {
    min-width: 80px;
  }
</style>
