// yourmet-sveltekit/src/lib/navbar/mobile-dropdowns/Art.svelte
<script>
  import { fade } from "svelte/transition";
  let mouseState = false;
</script>

<div class="mobileDropdown">
  <a class="mobileLink" on:click={()=> mouseState = !mouseState}><div>Art</div></a>
  {#if mouseState}
    <a class="mobileSublink" href="https://www.metmuseum.org/art/the-collection" target="_blank" rel="noreferrer"><div>The Met Collection</div></a>
    <a class="mobileSublink" href="https://www.metmuseum.org/about-the-met/collection-areas" target="_blank" rel="noreferrer"><div>Curatorial Areas</div></a>
    <a class="mobileSublink" href="https://www.metmuseum.org/about-the-met/conservation-and-scientific-research" target="_blank" rel="noreferrer"><div>Convservation and Scientific Research</div></a>
  {/if}
</div>

<style>
  .mobileLink {
    height: 52px;
    background-color: white;
    align-items: center;
    width: 340px;
  }
  .mobileSublink {
    height: 40px;
    background-color: white;
    align-items: center;
    width: 340px;
  }
  .mobileDropdown {
    display: flex;
    flex-direction: column;

  }
</style>

// src/navbar/dropdowns/Art.jsx
import { useState } from "react";

function ArtDropdown(props) {
  const [mouseState, showNavbar] = useState(false);

  function enterHandler(){
    showNavbar(true);
  }
  function exitHandler(){
    showNavbar(false);
  }
  return (
    <div className="bottombarLinks">
      <a href="#" rel="noreferrer" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>Art</a>
      {mouseState ?
      (<div className="dropdownMenu" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/visit/plan-your-visit" target="_blank" rel="noreferrer">The Met Collection</a></div>
        <div className="dropdownLinks"><a href="https://engage.metmuseum.org/admission" target="_blank" rel="noreferrer">Curatorial Areas</a></div>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/join-and-give/membership" target="_blank" rel="noreferrer">Convservation and Scientific Research</a></div>
      </div>)
      :
      null}
    </div>
  );
}

export default ArtDropdown;
