// yourmet-sveltekit/src/lib/navbar/dropdowns/Exhibitions.svelte
<script>
  import { fade } from "svelte/transition";
  let mouseState = false;
</script>

<div class="bottombarLinks" on:mouseenter={()=> mouseState = true} on:mouseleave={()=> mouseState = false}>
  <a href="#" rel="noreferrer" >Exhibitions and Events</a>
  {#if mouseState}
  <hr transition:fade={{duration: 100}} class="linkUnderline">
  {/if}
  {#if mouseState}
  <div class="dropdownMenu">
    <a href="https://www.metmuseum.org/exhibitions" target="_blank" rel="noreferrer"><div class="dropdownLinks">Exhibitions</div></a>
    <a href="https://www.metmuseum.org/events/whats-on" target="_blank" rel="noreferrer"><div class="dropdownLinks">Events and Tours</div></a>
    <a href="https://www.metmuseum.org/events/whats-on?tab=Events&categories=Performances" target="_blank" rel="noreferrer"><div class="dropdownLinks">Performances</div></a>
  </div>
  {/if}
</div>

<style>
  .bottombarLinks {
    min-width: 170px;
  }
</style>

// src/navbar/dropdowns/Exhibitions.jsx
import { useState } from "react";

function Exhibitions(props) {
  const [mouseState, showNavbar] = useState(false);

  function enterHandler(){
    showNavbar(true);
  }
  function exitHandler(){
    showNavbar(false);
  }
  return (
    <div className="bottombarLinks">
      <a href="#" rel="noreferrer" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>Exhibitions and Events</a>
      {mouseState ? (
      <><hr className="linkUnderline"></hr><div className="dropdownMenu" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/exhibitions" target="_blank" rel="noreferrer">Exhibitions</a></div>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/events/whats-on" target="_blank" rel="noreferrer">Events and Tours</a></div>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/events/whats-on?tab=Events&categories=Performances" target="_blank" rel="noreferrer">Performances</a></div>
      </div></>)
      :
      null
      }
    </div>
  );
}

export default Exhibitions;
