// yourmet-sveltekit/src/lib/navbar/mobile-dropdowns/Exhibitions.svelte
<script>
  import { fade } from "svelte/transition";
  let mouseState = false;
</script>

<div class="mobileDropdown">
  <a class="mobileLink" on:click={()=> mouseState = !mouseState}><div>Exhibitions and Events</div></a>
  {#if mouseState}
    <a class="mobileSublink" href="https://www.metmuseum.org/exhibitions" target="_blank" rel="noreferrer"><div>Exhibitions</div></a>
    <a class="mobileSublink" href="https://www.metmuseum.org/events/whats-on" target="_blank" rel="noreferrer"><div>Events and Tours</div></a>
    <a class="mobileSublink" href="https://www.metmuseum.org/events/whats-on?tab=Events&categories=Performances" target="_blank" rel="noreferrer"><div>Performances</div></a>
  {/if}
</div>

<style>
  .mobileLink {
    height: 52px;
    background-color: white;
    align-items: center;
    width: 340px;
  }
  .mobileSublink {
    height: 40px;
    background-color: white;
    align-items: center;
    width: 340px;
  }
  .mobileDropdown {
    display: flex;
    flex-direction: column;

  }
</style>

// src/navbar/dropdowns/Exhibitions.jsx
import { useState } from "react";

function Exhibitions(props) {
  const [mouseState, showNavbar] = useState(false);

  function enterHandler(){
    showNavbar(true);
  }
  function exitHandler(){
    showNavbar(false);
  }
  return (
    <div className="bottombarLinks">
      <a href="#" rel="noreferrer" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>Exhibitions and Events</a>
      {mouseState ? (
      <div className="dropdownMenu" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/exhibitions" target="_blank" rel="noreferrer">Exhibitions</a></div>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/events/whats-on" target="_blank" rel="noreferrer">Events and Tours</a></div>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/events/whats-on?tab=Events&categories=Performances" target="_blank" rel="noreferrer">Performances</a></div>
      </div>)
      :
      null
      }
    </div>
  );
}

export default Exhibitions;
