// yourmet-sveltekit/src/lib/navbar/dropdowns/Visit.svelte
<script>
  import { fade } from "svelte/transition";
  let mouseState = false;
</script>

<div class="bottombarLinks" on:mouseenter={()=> mouseState = true} on:mouseleave={()=> mouseState = false}>
  <a href="#" rel="noreferrer" >Visit</a>
  {#if mouseState}
  <hr transition:fade={{duration: 100}} class="linkUnderline">
  {/if}
  {#if mouseState}
  <div class="dropdownMenu">
    <a href="https://www.metmuseum.org/visit/plan-your-visit" target="_blank" rel="noreferrer">
      <div class="dropdownLinks">Plan Your Visit</div>
    </a>
    <a href="https://engage.metmuseum.org/admission" target="_blank" rel="noreferrer">
      <div class="dropdownLinks">Buy Tickets</div>
    </a>
    <a href="https://www.metmuseum.org/join-and-give/membership" target="_blank" rel="noreferrer">
      <div class="dropdownLinks">Become a Member</div>
    </a>
    <a href="https://maps.metmuseum.org/?screenmode=base&floor=1#hash=17/40.779448/-73.963517/-61" target="_blank" rel="noreferrer">
      <div class="dropdownLinks">Museum Map</div>
    </a>
    <a href="https://www.metmuseum.org/visit/dining" target="_blank" rel="noreferrer">
      <div class="dropdownLinks">Food and Drink</div>
    </a>
    <a href="https://www.metmuseum.org/visit/group-visits" target="_blank" rel="noreferrer">
      <div class="dropdownLinks">Group Visits</div>
    </a>
    <a href="https://www.metmuseum.org/visit/accessibility" target="_blank" rel="noreferrer">
      <div class="dropdownLinks">Accessibility</div>
    </a>
  </div>
  {/if}
</div>

<style>
  .bottombarLinks {
    min-width: 41px;
  }
</style>

// src/navbar/dropdowns/Visit.jsx
import { useState } from "react";

function VisitDropdown(props) {
  const [mouseState, showNavbar] = useState(false);

  function enterHandler(){
    showNavbar(true);
  }
  function exitHandler(){
    showNavbar(false);
  }
  return (
    <div className="bottombarLinks">
      <a href="#" rel="noreferrer" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>Visit</a>
      { mouseState ?
      (<><hr className="linkUnderline"></hr><div className="dropdownMenu" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/visit/plan-your-visit" target="_blank" rel="noreferrer">Plan Your Visit</a></div>
        <div className="dropdownLinks"><a href="https://engage.metmuseum.org/admission" target="_blank" rel="noreferrer">Buy Tickets</a></div>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/join-and-give/membership" target="_blank" rel="noreferrer">Become a Member</a></div>
        <div className="dropdownLinks"><a href="https://maps.metmuseum.org/?screenmode=base&floor=1#hash=17/40.779448/-73.963517/-61" target="_blank" rel="noreferrer">Museum Map</a></div>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/visit/dining" target="_blank" rel="noreferrer">Food and Drink</a></div>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/visit/group-visits" target="_blank" rel="noreferrer">Group Visits</a></div>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/visit/accessibility" target="_blank" rel="noreferrer">Accessibility</a></div>
      </div></>)
      :
      null
      }
    </div>
  );
}

export default VisitDropdown;
