// yourmet-sveltekit/src/lib/navbar/dropdowns/YourMet.svelte
<script>
  import { fade } from "svelte/transition";
  let mouseState = false;
</script>

<div class="bottombarLinks" on:mouseenter={()=> mouseState = true}  on:mouseleave={()=> mouseState = false}>
  <a href="#" rel="noreferrer" >YourMet</a>
  {#if mouseState}
  <hr transition:fade={{duration: 100}} class="linkUnderline">
  {/if}
  {#if mouseState}
  <div class="dropdownMenu">
    <a href="/login" target="_blank" rel="noreferrer">
      <div class="dropdownLinks">Your Account</div>
    </a>
  </div>
  {/if}
</div>

<style>
  .bottombarLinks {
    min-width: 70px;
  }
</style>

// yourmet-react/src/navbar/dropdowns/YourMet.jsx
import { useState } from "react";

function ResearchDropdown(props) {
  const [mouseState, showNavbar] = useState(false);

  function enterHandler(){
    showNavbar(true);
  }
  function exitHandler(){
    showNavbar(false);
  }
  return (
    <div className="bottombarLinks">
      <a href="#" rel="noreferrer" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>YourMet</a>
      {mouseState ?
      <><hr className="linkUnderline"></hr><div className="dropdownMenu" onMouseEnter={enterHandler} onMouseLeave={exitHandler}>
        <div className="dropdownLinks"><a href="https://www.metmuseum.org/art/libraries-and-research-centers" target="_blank" rel="noreferrer">Libraries and Research Centers</a></div>
      </div></>
      :
      null
      }
    </div>
  );
}

export default ResearchDropdown;
